CHF/urls.py
from django.conf.urls import patterns, url, include
from django.contrib import admin




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    
    #getting error, no module named 'manager.urls' with the line below:
    #url(r'^', include('manager.urls')),
    
    #url(r'^admin1/', manager.index, name='index'),
   
    # the django_mako_plus controller handles every request - this line is the glue that connects Mako to Django
    url(r'^.*$', 'django_mako_plus.controller.router.route_request' ),
]

manager/views/areascreate.py
from django_mako_plus.controller import view_function
from django.conf import settings
from .. import dmp_render, dmp_render_to_response
from django import forms
from catalog.models import Area, Event
from catalog import models as vmod
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.admin import widgets
from django.contrib.auth.decorators import login_required, permission_required

@view_function
@permission_required('catalog.add_area', raise_exception=True)
# check django docs to re-route to different URL: like login #
def process_request(request):
  
  param = request.urlparams[0]
  print(param + 'nothing')
  
  #process the form
  form = CreateAreaForm()
  if request.method == 'POST':  # just submitted the form
    form = CreateAreaForm(request.POST)
    if form.is_valid():
      a = Area()
      
      a.area_name = form.cleaned_data.get('name')
      a.description = form.cleaned_data.get('description')
      a.place_number = form.cleaned_data.get('place_number')
      a.event = Event.objects.get(id=param)

      
      a.save()
      return HttpResponseRedirect('/manager/events/eventsedit/'+param+'/')

      
  template_vars = {
    'form': form,
    'action':'/manager/areascreate/'+param+'/',
    'param': param,
  }
  return dmp_render_to_response(request, 'areascreate.html', template_vars)
  
  
class CreateAreaForm(forms.Form):
    name = forms.CharField(label='Area Name', required=True, max_length=100,widget=forms.TextInput(attrs={ 'class': 'form-control', 'style':'margin-left:20px'}))
    description = forms.CharField(label='Description', required=True, max_length=2000, widget=forms.TextInput(attrs={ 'class': 'form-control', 'style':'margin-left:20px'}))
    place_number = forms.CharField(label='Place Number', required=True, max_length=100, widget=forms.TextInput(attrs={ 'class': 'form-control', 'style':'margin-left:20px'}))
  
    def clean_username(self):
      name = self.cleaned_data.get('name')
      # check uniqueness of the username
      # method 1- returns the user OR raises exception
      #try:
      #  user = User.objects.get(username = username)
      #  raise forms.ValidationError('This username is already taken.')
      #except User.DoesNotExist as e:
      #  pass # this is what we hope for - means username is unique
      # method 2 -
      if Event.objects.filter(name=name).count() > 0:
        raise forms.ValidationError('This name is already taken.')
      return name

      
class CalendarWidget(forms.DateField):
  class Media:
    css = {
      'all':('/homepage/media/bootstrap3/css/bootstrap-datetimepicker.min.css',)
    }
    js = ('/homepage/media/bootstrap3/js/bootstrap-datetimepicker.min.js',)

manager/views/areasdelete.py
from django_mako_plus.controller import view_function
from django.conf import settings
from .. import dmp_render, dmp_render_to_response
from django import forms
from catalog.models import Area
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.admin import widgets
from django.contrib.auth.decorators import login_required, permission_required

@view_function
@permission_required('catalog.delete_area', raise_exception=True)
# check django docs to re-route to different URL: like login #
def process_request(request):
  
  param = request.urlparams[0]
  
  a = Area.objects.get(id=param)
  a.delete()
  
  return HttpResponseRedirect('/manager/events/')
  

manager/views/areasedit.py
from django_mako_plus.controller import view_function
from django.conf import settings
from .. import dmp_render, dmp_render_to_response
from django import forms
from catalog.models import Event, Area
from catalog import models as vmod
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, permission_required

@view_function
@permission_required('catalog.change_area', raise_exception=True)
# check django docs to re-route to different URL: like login #
def process_request(request):
  # make sure they're logged in
  # if not request.user.is_authenticated():
  # return HttpResponseRedirect('/manager/users/')
  # process the form
  
  param = request.urlparams[0]
  
  a = Area.objects.get(id=param)
  
  # filter retrieves all objects that match the filter. Get returns a single. All, returns all.
  form = AreasEditForm(initial={
    'name': a.area_name,
    'description': a.description,
    'place_number': a.place_number,
    


  })
  if request.method == 'POST':  # just submitted the form
    print('YES')
    form = AreasEditForm(request.POST)
    if form.is_valid():
      a.area_name = form.cleaned_data.get('name')
      a.description = form.cleaned_data.get('description')
      a.place_number = form.cleaned_data.get('place_number')
      
      a.save()
      return HttpResponseRedirect('/manager/events/')
      
  template_vars = {
    'form': form,
    'action':'/manager/areasedit/'+param+'/',

  }
  return dmp_render_to_response(request, 'areasedit.html', template_vars)
  
  
class AreasEditForm(forms.Form):
    
  name = forms.CharField(label='Area Name', required=True, max_length=100,widget=forms.TextInput(attrs={ 'class': 'form-control', 'style':'margin-left:20px'}))
  description = forms.CharField(label='Description', required=True, max_length=2000, widget=forms.TextInput(attrs={ 'class': 'form-control', 'style':'margin-left:20px'}))
  place_number = forms.CharField(label='Place Number', required=True, max_length=100, widget=forms.TextInput(attrs={ 'class': 'form-control', 'style':'margin-left:20px'}))

  
  
  pass
  

manager/views/events.py
# MANAGER USERS.PY
from django.conf import settings
from django_mako_plus.controller import view_function
from datetime import datetime
from .. import dmp_render, dmp_render_to_response
from catalog.models import Event
@view_function
def process_request(request):
    all_events = Event.objects.all()


    
    
    template_vars = {
      'all_events': all_events

    }
    print(all_events)
    return dmp_render_to_response(request, 'events.html', template_vars)

manager/views/eventscreate.py
from django_mako_plus.controller import view_function
from django.conf import settings
from .. import dmp_render, dmp_render_to_response
from django import forms
from catalog.models import Event
from catalog import models as vmod
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.admin import widgets


@view_function
@permission_required('catalog.add_event', raise_exception=True)
# check django docs to re-route to different URL: like login #
def process_request(request):
  
  #process the form
  form = CreateEventForm()
  if request.method == 'POST':  # just submitted the form
    form = CreateEventForm(request.POST)
    if form.is_valid():
      ev = Event()
      
      ev.name = form.cleaned_data.get('name')
      ev.description = form.cleaned_data.get('description')
      ev.start_date = form.cleaned_data.get('start_date')
      ev.image = form.cleaned_data.get('image')
      ev.end_date = form.cleaned_data.get('end_date')
      ev.add_date = form.cleaned_data.get('add_date')
      ev.venue = form.cleaned_data.get('venue')
      
      ev.save()
      return HttpResponseRedirect('/manager/events/')

      
  template_vars = {
    'form': form,
  }
  return dmp_render_to_response(request, 'Eventscreate.html', template_vars)
  
  
class CreateEventForm(forms.Form):
    name = forms.CharField(label='Event Name', required=True, max_length=100,widget=forms.TextInput(attrs={ 'class': 'form-control', 'style':'margin-left:20px'}))
    description = forms.CharField(label='Description', required=True, max_length=2000, widget=forms.TextInput(attrs={ 'class': 'form-control', 'style':'margin-left:20px'}))
    image = forms.CharField(label='Image', required=True, max_length=100, widget=forms.TextInput(attrs={ 'class': 'form-control', 'style':'margin-left:20px'}))
    start_date = forms.DateField(label='Start Date', required=True, widget=forms.TextInput())
    end_date = forms.DateField(label='End Date', required=True, widget=forms.TextInput())
    add_date = forms.DateField(label='Date Added', required=True, widget=forms.TextInput())
    venue = forms.ModelChoiceField(label='Venue', queryset=vmod.Venue.objects.order_by('venue_name'), required=True, widget=forms.Select())
    
    
    def clean_username(self):
      name = self.cleaned_data.get('name')
      # check uniqueness of the username
      # method 1- returns the user OR raises exception
      #try:
      #  user = User.objects.get(username = username)
      #  raise forms.ValidationError('This username is already taken.')
      #except User.DoesNotExist as e:
      #  pass # this is what we hope for - means username is unique
      # method 2 -
      if Event.objects.filter(name=name).count() > 0:
        raise forms.ValidationError('This name is already taken.')
      return name

      
class CalendarWidget(forms.DateField):
  class Media:
    css = {
      'all':('/homepage/media/bootstrap3/css/bootstrap-datetimepicker.min.css',)
    }
    js = ('/homepage/media/bootstrap3/js/bootstrap-datetimepicker.min.js',)

manager/views/eventsdelete.py
from django_mako_plus.controller import view_function
from django.conf import settings
from .. import dmp_render, dmp_render_to_response
from django import forms
from catalog.models import Event
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.admin import widgets
from django.contrib.auth.decorators import login_required, permission_required

@view_function
@permission_required('catalog.delete_event', raise_exception=True)
# check django docs to re-route to different URL: like login #
def process_request(request):
  
  param = request.urlparams[0]
  
  ev = Event.objects.get(id=param)
  ev.delete()
  
  return HttpResponseRedirect('/manager/events/')
  

manager/views/index.py
# MANAGER INDEX.PY
from django.conf import settings
from django_mako_plus.controller import view_function
from datetime import datetime
from .. import dmp_render, dmp_render_to_response

@view_function
def process_request(request):
    template_vars = {
      'now': datetime.now(),
    }
    return dmp_render_to_response(request, 'index.html', template_vars)

manager/views/products.py
# MANAGER USERS.PY
from django.conf import settings
from django_mako_plus.controller import view_function
from datetime import datetime
from .. import dmp_render, dmp_render_to_response
from catalog.models import Product, RentalProduct, IndividualProduct, BulkProduct

@view_function
def process_request(request):
    all_products = Product.objects.order_by('name')
    all_rental_products = RentalProduct.objects.all()
    all_individual_products = IndividualProduct.objects.all()
    all_bulk_products = BulkProduct.objects.all()
    
    template_vars = {
      'all_products': all_products,
      #'all_rental_products': all_rental_products,
      #'all_individual_products': all_individual_products,
      #'all_bulk_products': all_bulk_products,
    }
    print(all_products)
    return dmp_render_to_response(request, 'products.html', template_vars)

manager/views/productsdelete.py
from django_mako_plus.controller import view_function
from django.conf import settings
from .. import dmp_render, dmp_render_to_response
from django import forms
from catalog.models import Product
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.admin import widgets
from django.contrib.auth.decorators import login_required, permission_required

@view_function
@permission_required('catalog.delete_product', raise_exception=True)
# check django docs to re-route to different URL: like login #
def process_request(request):
  
  param = request.urlparams[0]
  
  pr = Product.objects.get(id=param)
  pr.delete()
  
  return HttpResponseRedirect('/manager/products/')
  

manager/views/users.py
# MANAGER USERS.PY
from django.conf import settings
from django_mako_plus.controller import view_function
from datetime import datetime
from .. import dmp_render, dmp_render_to_response
from account.models import User

@view_function
def process_request(request):
    all_users = User.objects.order_by('last_name')
    
    template_vars = {
      'all_users': all_users,
    }
    print(all_users)
    return dmp_render_to_response(request, 'users.html', template_vars)

manager/views/userscreate.py
from django_mako_plus.controller import view_function
from django.conf import settings
from .. import dmp_render, dmp_render_to_response
from django import forms
from account.models import User
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.admin import widgets
from django.contrib.auth.models import Permission, Group
from django.contrib.auth.decorators import login_required, permission_required

@view_function
@permission_required('account.add_user', raise_exception=True)
# check django docs to re-route to different URL: like login #

def process_request(request):
  
  #process the form
  form = CreateUserForm()
  if request.method == 'POST':  # just submitted the form
    form = CreateUserForm(request.POST)
    if form.is_valid():
      u = User()
      u.username = form.cleaned_data.get('username')
      u.first_name = form.cleaned_data.get('first_name')
      u.last_name = form.cleaned_data.get('last_name')
      u.address1 = form.cleaned_data.get('address1')
      u.address2 = form.cleaned_data.get('address2')
      u.set_password(form.cleaned_data.get('password'))
      u.email = form.cleaned_data.get('email')
      u.birth = form.cleaned_data.get('birthdate')
      u.phone_number = form.cleaned_data.get('phone_number')
      
      perms = form.cleaned_data.get('user_permissions')
      groups = form.cleaned_data.get('groups')
      u.save()
      
      u.user_permissions.clear()
      for x in perms:
        u.user_permissions.add(x)
        print(x)
        
      u.groups.clear()
      for x in groups:
        u.groups.add(x)
        print(x)
      u.save()
      
     
      
      #u2 = UserUserGroups()
      
      #u2.user_id = u.id
      #u2.permission_id = form.cleaned_data.get('user_permissions')
      #u2.group = form.cleaned_data.get('groups')
      
      #u.save()
      #u2.save()
      # authenticate(username=form.cleaned_data.get('username'),password=form.cleaned_data.get('password'))
      # login(request, form.user)    
      # create a user object
      # fill the user object with the data from the form
      return HttpResponseRedirect('/manager/users/')
      
  template_vars = {
    'form': form,
  }
  return dmp_render_to_response(request, 'userscreate.html', template_vars)
  
  
class CreateUserForm(forms.Form):
    username = forms.CharField(label='Username', required=True, max_length=100, widget=forms.TextInput())
    first_name = forms.CharField(label='First Name', required=True, max_length=100, widget=forms.TextInput())
    last_name = forms.CharField(label='Last Name', required=True, max_length=100, widget=forms.TextInput())
    phone_number = forms.CharField(label='Phone Number', required=True, max_length=20, widget=forms.TextInput())
    email = forms.EmailField(label='Email', required=True, max_length=60, widget=forms.EmailInput())
    address1 = forms.CharField(label='Address 1', required=True, max_length=100, widget=forms.TextInput())
    address2 = forms.CharField(label='Address 2', required=True, widget=forms.TextInput())
    birthdate = forms.DateField(label='Birth Date', required=True, widget=forms.TextInput())
    password = forms.CharField(label='Password', required=True, max_length=100, widget=forms.PasswordInput())
    password2 = forms.CharField(label='Password (again)', required=True, max_length=100, widget=forms.PasswordInput())
    groups = forms.ModelMultipleChoiceField(label='Groups', required=False, queryset=Group.objects.order_by('name'), widget=forms.CheckboxSelectMultiple())
    user_permissions = forms.ModelMultipleChoiceField(label='User Permissions', required=False, queryset=Permission.objects.all(), widget=forms.CheckboxSelectMultiple())
    
    def clean_username(self):
      username = self.cleaned_data.get('username')
      # check uniqueness of the username
      # method 1- returns the user OR raises exception
      #try:
      #  user = User.objects.get(username = username)
      #  raise forms.ValidationError('This username is already taken.')
      #except User.DoesNotExist as e:
      #  pass # this is what we hope for - means username is unique
      # method 2 -
      if User.objects.filter(username=username).count() > 0:
        raise forms.ValidationError('This username is already taken.')
      return username
      
      
    def clean(self):
      if self.cleaned_data.get('password') != self.cleaned_data.get('password2'):
        raise forms.ValidationError('Your passwords do not match.')
      return self.cleaned_data
      
class CalendarWidget(forms.DateField):
  class Media:
    css = {
      'all':('/homepage/media/bootstrap3/css/bootstrap-datetimepicker.min.css',)
    }
    js = ('/homepage/media/bootstrap3/js/bootstrap-datetimepicker.min.js',)

manager/templates/areasedit.html
<%inherit file="base_app.htm" />

<%block name="title">
	Edit Area
</%block>
<%block name="content_top">
<ol class="breadcrumb">
  <li><a href="/manager/index/">Admin Dashboard</a></li>
	<li><a href="/manager/events/">Events</a></li>
  <li class="disabled"><a href="#">Edit Area</a></li>
</ol>
<h1 class="title text-center">
	Edit Area
</h1>
<hr>
</%block>
<%block name="content">

<div class="col-md-7 text-left">
<form method='POST' action=${action} id='AreasEditForm'>
	<table>
  	${ form }
  </table>

	<a href="/manager/events/" class="btn btn-danger" style="margin-left:50px; margin-top:30px">Cancel</a>
  <button class="btn btn-primary" type="submit" style="margin-left:50px; margin-top:30px">Make Changes</button>
</form>
</%block>

manager/templates/base.htm
## this is the skeleton of all pages on in this app - it defines the basic html tags

## set up a StaticRenderer object to enable the CSS/JS automatic inclusion magic.
<%! from django_mako_plus.controller import static_files %>
<%  static_renderer = static_files.StaticRenderer(self) %>

<!DOCTYPE html>
<html>
  <meta charset="UTF-8">
  <head>
    
    <title>manager</title>
    
    ## add any site-wide scripts or CSS here; for example, jquery:
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  
    ## render the css with the same name as this page
    ${ static_renderer.get_template_css(request, context)  }
  
  </head>
  <body>
  
    <header>
      Welcome to the manager app!
    </header>
  
    <%block name="content">
      Site content goes here in sub-templates.
    </%block>  
  
    ## render the JS with the same name as this page
    ${ static_renderer.get_template_js(request, context)  }
  
  </body>
</html>

manager/templates/base_ajax.htm
## this is the skeleton of all *ajax* pages on our site - page snippets that are retrieved with Ajax.
## it's primary function is to insert the CSS and JS for the template hierarchy the ajax return
## is composed of.

## set up a StaticRenderer object to enable the CSS/JS automatic inclusion magic.
<%! from django_mako_plus.controller import static_files %>
<%  static_renderer = static_files.StaticRenderer(self) %>

## render the CSS for this template
${ static_renderer.get_template_css(request, context)  }

## render the ajax content
<%block name="content">
  Sub-templates should place their ajax content here.
</%block>  

## render the JS for this template (placed here at the end because browsers apparently load faster when JS is at the end)
${ static_renderer.get_template_js(request, context)  }

manager/templates/events.html
<%inherit file="base_app.htm" />

<%block name="content">
<ol class="breadcrumb">
  <li><a href="/manager/index/">Admin Dashboard</a></li>
	<li><a href="/manager/users/">Users</a></li>
	<li><a href="/manager/products/">Products</a></li>
	<li><a href="/manager/venues/">Venues</a></li>
  <li class="active"><a href="/manager/events/">Events</a></li>
</ol>
<div class="col-md-12">
	<h2 class="text-center" style="margin-bottom:25px">Event List</h2>
</div>

<table class="table table-striped">
	<tr>
		<th>Event Name:</th>
		<th>Image:</th>
		<th>Description:</th>
		<th>Start Date:</th>
		<th>End Date:</th>
		<th>Date Added:</th>
		<th>Venue:</th>
		<th></th>
		<th>Actions:</th>
	</tr>
		%for Event in all_events:
  <tr>
			<td>${Event.name}</td>
			<td>${Event.image}</td>
      <td>${Event.description}</td>
			<td>${Event.start_date}</td>
			<td>${Event.end_date}</td>
			<td>${Event.add_date}</td>
			<td>${Event.venue_id}</td>
			<td></td>
			<td><a href="/manager/eventsedit/${Event.id}/">Edit</a> |
				 <a href="/manager/eventsdelete/${Event.id}/" class="delete_button">Delete</a>
  </tr>
	
    %endfor
	</table>
	
<a id="create_user_button" href="/manager/eventscreate/" class="btn btn-sm btn-warning" style="float:right; margin-bottom:5px">New Event</a>
	
	<!--MODAL DELETE-->
<div class="modal fade" id = "delete_modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Confirmation Requested</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete this product?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-warning" data-dismiss="modal">No, Cancel</button>
				<!--USE JS TO GRAB THE LINK FROM THE DELETE BUTTON ABOVE-->
        <a id="confirm_delete_button" href="" class="btn btn-danger">Yes, Delete</a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
		

</%block>

manager/templates/eventsedit.html
<%inherit file="/homepage/templates/base_app.htm" />

<%block name="title">
	Edit Venue
</%block>
<%block name="content_top">
<ol class="breadcrumb">
  <li><a href="/manager/index/">Admin Dashboard</a></li>
	<li><a href="/manager/events/">Events</a></li>
  <li class="disabled"><a href="#">Edit Event</a></li>
</ol>
<h1 class="title text-center">
	Edit Event
</h1>
<hr>
</%block>
<%block name="content">

<div class="col-md-7 text-left">
<form method='POST' action=${action} id='EventsEditForm'>
	<table>
  	${ form }
  </table>
  <script type="text/javascript">
      $(function () {
        $('#id_start_date').datetimepicker({
               format: 'MM/DD/YYYY'
         });
         $('#id_end_date').datetimepicker({
                format: 'MM/DD/YYYY'
          });
          $('#id_add_date').datetimepicker({
                 format: 'MM/DD/YYYY'
           });
      });
  </script>
	<a href="/manager/events/" class="btn btn-danger" style="margin-left:50px; margin-top:30px">Cancel</a>
  <button class="btn btn-primary" type="submit" style="margin-left:50px; margin-top:30px">Make Changes</button>
</form>
<br>
<div class="col-md-12">
	<h4 class="text-center" style="margin-bottom:25px">Areas for Event</h4>
</div>

<table class="table table-striped">
	<tr>
		<th>Area Name:</th>
		<th>Description:</th>
		<th>Place Number:</th>

		<th></th>
		<th>Actions:</th>
	</tr>
		%for Area in all_areas:
  <tr>
			<td>${Area.area_name}</td>
			<td>${Area.description}</td>
      <td>${Area.place_number}</td>

			<td></td>
			<td><a id="editbutton" href="/manager/areasedit/${Area.id}/">Edit</a> |
				 <a href="/manager/areasdelete/${Area.id}/" class="delete_button">Delete</a>
  </tr>
	
    %endfor
	</table>
	<a id="create_area_button" href="/manager/areascreate/${param}/" class="btn btn-sm btn-warning" style="float:right; margin-bottom:5px">New Area</a>
	
		<!--MODAL DELETE-->
	<div class="modal fade" id = "delete_modal" tabindex="-1" role="dialog">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title">Confirmation Requested</h4>
	      </div>
	      <div class="modal-body">
	        <p>Are you sure you want to delete this product?</p>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-warning" data-dismiss="modal">No, Cancel</button>
					<!--USE JS TO GRAB THE LINK FROM THE DELETE BUTTON ABOVE-->
	        <a id="confirm_delete_button" href="" class="btn btn-danger">Yes, Delete</a>
	      </div>
	    </div><!-- /.modal-content -->
	  </div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
</%block>

manager/templates/productscreate.html
<%inherit file="base_app.htm" />

<%block name="title">
	Create Product
</%block>
<%block name="content_top">
<ol class="breadcrumb">
  <li><a href="/manager/index/">Admin Dashboard</a></li>
	<li><a href="/manager/products/">Products</a></li>
  <li class="active"><a href="/manager/productscreate/">New Product</a></li>
</ol>
<h1 class="title text-center">
	Create Product
</h1>
<hr>
</%block>
<%block name="content">
<div class="col-md-7 text-left">
<form method="POST" action="/manager/productscreate/">
  <table>
      ${ form.as_p() }
  </table>
  <script type="text/javascript">
      $(function () {
          $('#id_birthdate').datetimepicker({
                 format: 'MM/DD/YYYY'
           });
      });
  </script>
  <button class="btn btn-primary" type="submit" style="margin-left:30px">Create</button>
</form>

				       



</%block>

manager/templates/productsedit.html
<%inherit file="base_app.htm" />

<%block name="title">
	Edit Product
</%block>
<%block name="content_top">
<ol class="breadcrumb">
  <li><a href="/manager/index/">Admin Dashboard</a></li>
	<li><a href="/manager/products/">Products</a></li>
  <li class="disabled"><a href="#">Edit Product</a></li>
</ol>
<h1 class="title text-center">
	Edit Product
</h1>
<hr>
</%block>
<%block name="content">

<div class="col-md-7 text-left">
<form method='POST' action=${action} id='ProductsEditForm'>
	<table>
  	${ form }
  </table>
  <script type="text/javascript">
      $(function () {
          $('#id_birthdate').datetimepicker({
                 format: 'MM/DD/YYYY'
           });
      });
  </script>
	<a href="/manager/products/" class="btn btn-danger" style="margin-left:50px; margin-top:30px">Cancel</a>
  <button class="btn btn-primary" type="submit" style="margin-left:50px; margin-top:30px">Make Changes</button>
</form>
</%block>

manager/templates/userscreate.html
<%inherit file="base_app.htm" />

<%block name="title">
	Create User
</%block>
<%block name="content_top">
<ol class="breadcrumb">
  <li><a href="/manager/index/">Admin Dashboard</a></li>
	<li><a href="/manager/users/">Users</a></li>
  <li class="active"><a href="/manager/userscreate/">New User</a></li>
</ol>
<h1 class="title text-center">
	Create User
</h1>
<hr>
</%block>
<%block name="content">
<div class="col-md-12 text-left">
<form method="POST" action="/manager/userscreate/">
  <table>
      ${ form.as_p() }
  </table>
  <script type="text/javascript">
      $(function () {
          $('#id_birthdate').datetimepicker({
                 format: 'MM/DD/YYYY'
           });
      });
  </script>
  <button class="btn btn-primary" type="submit" style="margin-left:30px">Create</button>
</form>

				       



</%block>

manager/templates/venuesedit.html
<%inherit file="base_app.htm" />

<%block name="title">
	Edit Venue
</%block>
<%block name="content_top">
<ol class="breadcrumb">
  <li><a href="/manager/index/">Admin Dashboard</a></li>
	<li><a href="/manager/products/">Venues</a></li>
  <li class="disabled"><a href="#">Edit Venue</a></li>
</ol>
<h1 class="title text-center">
	Edit Venue
</h1>
<hr>
</%block>
<%block name="content">

<div class="col-md-7 text-left">
<form method='POST' action=${action} id='VenuesEditForm'>
	<table>
  	${ form }
  </table>
  <script type="text/javascript">
      $(function () {
          $('#id_birthdate').datetimepicker({
                 format: 'MM/DD/YYYY'
           });
      });
  </script>
	<a href="/manager/products/" class="btn btn-danger" style="margin-left:50px; margin-top:30px">Cancel</a>
  <button class="btn btn-primary" type="submit" style="margin-left:50px; margin-top:30px">Make Changes</button>
</form>
</%block>